### ISSUE TITLE
rework shape collection

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridges-cxx#89]
There  is a need to clarify responsibilities in a few data structures, but it is particularly true in the shape collection. Whose responsibility is it to clean up the memory associated with the shapes? Is it the responsibility of the shape collection to clean up the shape it contains, or is it the reponsibility of the external code to do so?

A few  of the data structures have the very same issue.

**Comment by krs-world** [comment]
Similar to the graph. If the shape allocates memory internally, then it should free that up on its deletion or goes out of scope. Whatever the user allocates he/she needs to free.

I will take a look at it  as the data structure requires more work.
      -- krs

**Comment by krs-world** [comment]
Looking at the shape  classes, only the SymbolCollection seems to be using pointers. We can change that to using references and then we wont have any issues with allocated memory. The remaining classes (Rectangle, Circle, etc) dont use any allocated memory). I can modify this for the C++ version..

**Comment by krs-world** [comment]
I have updated the SymbolCollection class - it still accepts addresses of symbols (needed since we are trying to use polymorphism), however the user can create the symbols and simply end addresses of the symbols he createts and not have to do any allocation. No allocation is being done  in the shape classes. I think we are good and I got the test working again.

**Comment by krs-world** [comment]
Made additional changes to the shape collection so that the user only does not have to use addresses to add symbols. The only place addresses are used in maintaining the map of symbols, which is internal to the client (need to do that since  Symbol is abstract and can  instantiate an abstract class).  The c++ shape collection test has been updated, but other applications using the symbol collection will break!  The main changes are   in adding symbols:

Rectangle r1;

s1->addSymbol(r1);

where r1 is passed by reference.
