### ISSUE TITLE
sio_client.h error

### ISSUE THREAD

**Issue by krs-world** [BridgesUNCC/bridges-cxx#97]
Getting this error:

c++ -g -o display_game display_game.cpp -g -I/Users/kalpathi/gr/bridges/cxx/src/  -I/usr/local/curl764/include  -I/usr/local/rapidjson/include -DTESTING=1 -std=c++14  -L/usr/local/curl764//lib  -lcurl -l pthread 
In file included from display_game.cpp:1:
In file included from /Users/kalpathi/gr/bridges/cxx/src/NonBlockingGame.h:4:
In file included from /Users/kalpathi/gr/bridges/cxx/src/GameBase.h:4:
/Users/kalpathi/gr/bridges/cxx/src/SocketConnection.h:4:10: fatal error: 'sio_client.h' file
      not found
#include "sio_client.h"
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [display_game] Error 1

**Comment by esaule** [comment]
The problem is not in the code, it is in how you compile it.

A user would pass -I of the include directory we give them, -L of the
lib directory we give them and link against curl, pthread, and
bridges. (Note that your makefile seem not to have the -l bridges it
should have.)

Here you want to have use the current version of bridges and not the
packaged one, so what I do is that I pass -I of the bridges package in
LOCALCXXFLAGS in env_vars.mk

It is important to pass it in LOCALCXXFLAGS because it gets listed
after the development one in the compiler parameters so it is scanned
after. In other words, you get the library headers from the
distributed package and bridges headers from the bridges package which
is probably what you want.

You also do not want to use your own rapidjson, you want to use the
one that comes from the package. (If the versions are different
between the one compiled in libbridges.a and the one you include,
strange things can happen.)

The C++ parameters in my env_var.mk look like:

BRIDGESCXX=/home/erik/work/bridges/bridges-cxx
BRIDGESCXX-INSTALL=/home/erik/prgs/bridges-cxx-install

LOCALLDFLAGS=-L ${BRIDGESCXX-INSTALL}/lib/

LOCALCXXFLAGS= -O0 -I $(BRIDGESCXX-INSTALL)/include


BRIDGES_INCL=/home/erik/work/bridges/bridges-cxx/src/
CURL_LIB_PATH=/home/erik/prgs/curl/lib
CURL_INCL=/home/erik/prgs/curl/include
#RAPID_JSON_INCL=/home/erik/prgs/rapidjson/include
RAPID_JSON_INCL=${BRIDGESCXX-INSTALL}/include
CURL_LIB=curl

Hoping this helps

Erik

On Tue, Aug 06, 2019 at 07:11:42AM -0700, Kalpathi Subramanian wrote:
> Getting this error:
> 
> c++ -g -o display_game display_game.cpp -g -I/Users/kalpathi/gr/bridges/cxx/src/  -I/usr/local/curl764/include  -I/usr/local/rapidjson/include -DTESTING=1 -std=c++14  -L/usr/local/curl764//lib  -lcurl -l pthread 
> In file included from display_game.cpp:1:
> In file included from /Users/kalpathi/gr/bridges/cxx/src/NonBlockingGame.h:4:
> In file included from /Users/kalpathi/gr/bridges/cxx/src/GameBase.h:4:
> /Users/kalpathi/gr/bridges/cxx/src/SocketConnection.h:4:10: fatal error: 'sio_client.h' file
>       not found
> #include "sio_client.h"
>          ^~~~~~~~~~~~~~
> 1 error generated.
> make: *** [display_game] Error 1
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BridgesUNCC/bridges-cxx/issues/97

-- 
Dr Erik Saule
Associate Professor at University of North Carolina at Charlotte (UNCC)
tel: +1 (704) 687-8580
web: http://webpages.uncc.edu/~esaule/
== 
Perform academic literature search on http://theadvisor.osu.edu/
